<div style="color: rgb(34, 34, 34); font-family: arial; font-size: small; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
                <div>
                    <br class="Apple-interchange-newline" />
                    <table border="1" cellpadding="0" cellspacing="0" class="" 
                        style="width: 466pt; margin-left: -1.7pt; border-collapse: collapse; border: none;" 
                        width="621">
                        <thead>
                            <tr style="height: 1cm;">
                                <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border: 1pt solid windowtext; padding: 0cm 5.4pt; height: 1cm;" 
                                    width="142">
                                    <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                        <span style="font-size: 14pt; font-family: 標楷體; color: black;">計費項目</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                        </span>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                    </p>
                                </td>
                                <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                    width="369">
                                    <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                        <span style="font-size: 14pt; font-family: 標楷體; color: black;">定義說明</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                        </span>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                    </p>
                                </td>
                                <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                    width="120">
                                    <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                        <span style="font-size: 14pt; font-family: 標楷體; color: blue;">所得稅代號</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;"><p></p>
                                        </span>
                                        <p>
                                        </p>
                                        <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                            <span lang="EN-US" 
                                                style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">(</span><span 
                                                style="font-size: 14pt; font-family: 標楷體; color: blue;">前</span><span 
                                                lang="EN-US" 
                                                style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">2</span><span 
                                                style="font-size: 14pt; font-family: 標楷體; color: blue;">碼</span><span 
                                                lang="EN-US" 
                                                style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">)</span><span 
                                                lang="EN-US" 
                                                style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p>
                                            </p>
                                            </span>
                                            <p>
                                            </p>
                                            <p>
                                            </p>
                                            <p>
                                            </p>
                                            <p>
                                            </p>
                                            <p>
                                            </p>
                                        </p>
                                    </p>
                                </td>
                            </tr>
                        </thead>
                        <tr style="height: 22.7pt;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="142">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">全年累計超過當月投保金額</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                        <span lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">4</span><span 
                                            style="font-size: 14pt; font-family: 標楷體; color: black;">倍部分的獎金</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p>
                                        </p>
                                        </span>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="369">
                                <p align="left" class="" style="line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">
                                    給付被保險人薪資所得中，未列入投保金額計算且具獎勵性質的各項給予</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">(</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">如年終獎金、節金、紅利等</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">)</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">，累計超過當月投保金額</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">4</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">倍部分。</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="120">
                                <p align="center" class="" 
                                    style="margin-left: 42.75pt; text-align: center; text-indent: -42.75pt; line-height: 16pt;">
                                    <b><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">50<p></p>
                                    </span></b>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 22.7pt;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="142">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">
                                    兼職薪資所得</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.3pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="369">
                                <p align="left" class="" style="line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">給付兼職人員</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">(</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">指非在本單位投保健保</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">)</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">的薪資所得。</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="120">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <b><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">50</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span></b>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 22.7pt;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="142">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">
                                    執行業務收入</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.3pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="369">
                                <p align="left" class="" style="line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">
                                    給付民眾的執行業務收入，不扣除必要費用或成本。</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="120">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <b><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.3pt;">
                                    9A</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: blue; letter-spacing: -0.3pt;">、</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.3pt;">9B</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span></b>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="142">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">股利所得</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="369">
                                <p align="left" class="" style="line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">公司給付民眾的股利總額。</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="120">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <b><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">54</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span></b>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 22.7pt;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="142">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">利息所得</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="369">
                                <p align="left" class="" style="line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">
                                    給付民眾公債、公司債、金融債券、各種短期票券、存款及其他貸出款項的利息。</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 22.7pt;" 
                                width="120">
                                <p class="" style="margin-left: 14.4pt; line-height: 16pt;">
                                    <b><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;">
                                    5A</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: blue; letter-spacing: -0.5pt;">、</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;">5B</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: blue; letter-spacing: -0.5pt;">、</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;"><p></p>
                                    </span></b>
                                    <p>
                                    </p>
                                    <p class="" 
                                        style="margin-left: 54.1pt; text-indent: -39.7pt; line-height: 16pt;">
                                        <b><span lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;">
                                        5C</span><span 
                                            style="font-size: 14pt; font-family: 標楷體; color: blue; letter-spacing: -0.5pt;">、</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;">52</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p>
                                        </p>
                                        </span></b>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 106.3pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="142">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">租金收入</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 276.4pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="369">
                                <p align="left" class="" style="line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">
                                    給付民眾的租金（未扣除必要損耗及費用）。</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 90.35pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="120">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <b><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;">51</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span></b>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                    </table>
                    <br />
                </div>
                <div>
                    <table border="1" cellpadding="0" cellspacing="0" class="" 
                        style="width: 467.8pt; margin-left: -1.7pt; border-collapse: collapse; border: none;" 
                        width="624">
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border: 1pt solid windowtext; padding: 0cm 5.4pt; height: 1cm;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">計費項目</span><span 
                                        lang="EN-US" style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">下　限</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -1pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: solid solid solid none; border-top-color: windowtext; border-right-color: windowtext; border-bottom-color: windowtext; border-top-width: 1pt; border-right-width: 1pt; border-bottom-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">上　限</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 34pt;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 34pt;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.6pt;">
                                    全年累計超過當月投保金額</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -1pt;">4</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -1pt;">倍部分的獎金</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.6pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 34pt;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">無</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.6pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 34pt;" 
                                width="250">
                                <p class="" style="text-align: justify; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">
                                    獎金累計超過當月投保金額</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.3pt;">4</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">倍後，超過的部分單次以</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.3pt;">1,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">萬元為限。</span><span 
                                        lang="EN-US" style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">
                                    兼職薪資所得</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.3pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td 
                                style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">單次給付達基本工資</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';">21,009</span><span 
                                        style="font-size: 14pt; font-family: 標楷體;">元</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td 
                                style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">單次給付以</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.8pt;">1,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">萬元為限</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.8pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>                        							

                        </tr>
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">
                                    執行業務收入</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.3pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td 
                                style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">單次給付達</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';">20,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體;">元</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td 
                                style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">單次給付以</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.8pt;">1,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">萬元為限</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.8pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>							
                        </tr>
                        <tr style="height: 34pt;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 34pt;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 16pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">股利所得</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 34pt;" 
                                width="250">
                                <p class="" 
                                    style="margin-left: 9.05pt; text-align: justify; text-indent: -11.9pt; line-height: 16pt;">
                                    <span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">1.<span 
                                        style="font-size: 7pt; line-height: normal;"><span 
                                        class="Apple-converted-space">&nbsp;</span></span></span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">以雇主或自營業主身分投保者：單次給付金額超過已列入投保金額計算部分達</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">20,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">元。</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p class="" 
                                        style="margin-left: 9.05pt; text-align: justify; text-indent: -11.9pt; line-height: 16pt;">
                                        <span lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.4pt;">
                                        2.<span style="font-size: 7pt; line-height: normal;">&nbsp;&nbsp;<span 
                                            class="Apple-converted-space">&nbsp;</span></span></span><span 
                                            style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.4pt;">非以雇主或自營業主身分投保者：單次給付達</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.4pt;">20,000</span><span 
                                            style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.4pt;">元。</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -0.4pt;"><p>
                                        </p>
                                        </span>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 34pt;" 
                                width="250">
                                <p class="" 
                                    style="margin-left: 9.05pt; text-align: justify; text-indent: -11.9pt; line-height: 16pt;">
                                    <span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">1.<span 
                                        style="font-size: 7pt; line-height: normal;"><span 
                                        class="Apple-converted-space">&nbsp;</span></span></span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -0.3pt;">以</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">雇主或自營業主身分投保者：單次給付金額超過已列入投保金額計算部分以</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;">1,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; color: black;">萬元為限。</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: black;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p class="" 
                                        style="margin-left: 9.05pt; text-align: justify; text-indent: -11.9pt; line-height: 16pt;">
                                        <span lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -1pt;">
                                        2.<span style="font-size: 7pt; line-height: normal;">&nbsp;&nbsp;<span 
                                            class="Apple-converted-space">&nbsp;</span></span></span><span 
                                            style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -1pt;">非以雇主或自營業主身分投保者：單次給付以</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -1pt;">1,000</span><span 
                                            style="font-size: 14pt; font-family: 標楷體; color: black; letter-spacing: -1pt;">萬元為限。</span><span 
                                            lang="EN-US" 
                                            style="font-size: 14pt; font-family: 'Times New Roman'; color: black; letter-spacing: -1pt;"><p>
                                        </p>
                                        </span>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                        <p>
                                        </p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">利息所得</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue; letter-spacing: -0.5pt;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 18pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">單次給付達</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';">20,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體;">元</span></p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">單次給付以</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.8pt;">1,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">萬元為限</span><span 
                                        lang="EN-US" style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                        <tr style="height: 1cm;">
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 92.15pt; border-style: none solid solid; border-right-color: windowtext; border-bottom-color: windowtext; border-left-color: windowtext; border-right-width: 1pt; border-bottom-width: 1pt; border-left-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="123">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; color: black;">租金收入</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; color: blue;"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.8pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體;">單次給付達</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';">20,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體;">元</span><span lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                            <td style="margin: 0px; font-family: arial, sans-serif; width: 187.85pt; border-style: none solid solid none; border-bottom-color: windowtext; border-bottom-width: 1pt; border-right-color: windowtext; border-right-width: 1pt; padding: 0cm 5.4pt; height: 1cm;" 
                                width="250">
                                <p align="center" class="" style="text-align: center; line-height: 17pt;">
                                    <span style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">單次給付以</span><span 
                                        lang="EN-US" 
                                        style="font-size: 14pt; font-family: 'Times New Roman'; letter-spacing: -0.8pt;">1,000</span><span 
                                        style="font-size: 14pt; font-family: 標楷體; letter-spacing: -0.8pt;">萬元為限</span><span 
                                        lang="EN-US" style="font-size: 14pt; font-family: 'Times New Roman';"><p></p>
                                    </span>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                    <p>
                                    </p>
                                </p>
                            </td>
                        </tr>
                    </table>
                </div>
                <div>
                </div>
            </div>